In [1]:
import numpy as np

_____
**Exercise 1**

Create a vector with values in the range 10 to 49.

In [2]:
vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

_____
**Exercise 2**

Create a 3x3 matrix with values from 0 to 8.

In [3]:
matrix = np.arange(0, 9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

_____
**Exercise 3**

Find the non-zero indexes of the array

In [4]:
array = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])
array.nonzero()

(array([ 0,  1,  2,  3,  4,  6, 10, 11, 12, 13, 14], dtype=int64),)

_____
**Exercise 4**

Create a 6x6 identity matrix.

In [5]:
matrix_2 = np.identity(6) 
matrix_2

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

_____
**Exercise 5**

Find the indices of the minimum and maximum values of the matrix created in exercise 2.

In [6]:
matrix.argmin()

0

In [7]:
matrix.argmax()

8

**Exercise 6**

Create a 10x10 matrix with 1 on the edges and 0 on the inside.

In [8]:
matriz_3 = np.ones([10, 10])
matriz_3[1:-1, 1:-1] = 0
matriz_3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

_____
**Exercise 7**

Create a 5x5 matrix with values in each row ranging from 0 to 4.

In [9]:
matrix_4 = np.tile(np.arange(0, 5), 5).reshape(5, 5) 
matrix_4

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

_____
**Exercise 8**

Create two random arrays named A and B. Check if they are equal.

In [10]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))

np.equal(A, B)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

_____
**Exercise 9**

Create a 20x20 matrix of random values between 1 and 100, then indicate their mean, median, mode, and standard deviation. Values that result in more than two numbers after the comma as floating points must have a maximum of 2.

In [11]:
np.random.seed(0)
matrix_5 = np.random.randint(1, 101, (20, 20))

In [12]:
# media
round(np.mean(matrix_5), 2) 

49.86

In [13]:
# median
round(np.median(matrix_5), 2) 

48.0

In [14]:
# standard deviation
round(np.std(matrix_5)) 

29

In [15]:
from scipy import stats

In [16]:
# mode
stats.mode(matrix_5) 

ModeResult(mode=array([[ 1, 11, 26, 36,  4, 10, 70,  4, 41, 33, 20, 12, 83, 94,  1,  1,
        30, 14,  6, 15]]), count=array([[1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]))

_____
**Exercise 10**

Create two arrangements of 4 integer elements and do the following operations: add them, subtract the second from the first, multiply them, divide the first by the second. Do it using methods.

In [17]:
np.random.seed(0) 
C = np.random.randint(1, 100, 4) 
D = np.random.randint(1, 100, 4)
print(C)
print(D)

[45 48 65 68]
[68 10 84 22]


In [18]:
# C + D
np.add(C, D) 

array([113,  58, 149,  90])

In [19]:
# C - D
np.subtract(C, D) 

array([-23,  38, -19,  46])

In [20]:
# C * D
np.multiply(C, D) 

array([3060,  480, 5460, 1496])

In [21]:
# C / D
np.divide(C, D) 

array([0.66176471, 4.8       , 0.77380952, 3.09090909])

_____
**Exercise 11**

Create a 4x4 array of random values ​​between 1 and 10, and then add a row of 0s to the end.

In [22]:
np.random.seed(0)
matrix_6 = np.random.randint(1, 11, (4, 4))
print(matrix_6)
print()
matrix_6 = np.vstack([matrix_6, np.zeros(4)])
print(matrix_6)

[[ 6  1  4  4]
 [ 8 10  4  6]
 [ 3  5  8  7]
 [ 9  9  2  7]]

[[ 6.  1.  4.  4.]
 [ 8. 10.  4.  6.]
 [ 3.  5.  8.  7.]
 [ 9.  9.  2.  7.]
 [ 0.  0.  0.  0.]]


_____
**Exercise 12**

Create an array of 4 elements between 0 and 10, report the number of elements it has and also how many bytes the array occupies.

In [23]:
np.random.seed(0)
array_2 = np.random.randint(0, 11, (1, 4))
array_2

array([[5, 0, 3, 3]])

In [24]:
# bytes of each element
array_2.itemsize # bytes de cada elemento

4

In [25]:
# number of elements
array_2.size 

4

In [26]:
# bytes total of the array
array_2.nbytes 

16