_____
### Exercise 1

1. Open the CSV file.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/joanby/python-ml-course/master/datasets/titanic/titanic3.csv')
df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

_____
2. Get the names of all the columns, then iterate that object and print the following row by row: "Null values in Survived: 10" where 10 is the total of null or missing values in the Survived column.

In [3]:
column = df.columns.values

for i in column:    
    total_null = df[i].isnull().sum()
    print(f'Null values in {i}: {total_null}')

Null values in pclass: 0
Null values in survived: 0
Null values in name: 0
Null values in sex: 0
Null values in age: 263
Null values in sibsp: 0
Null values in parch: 0
Null values in ticket: 0
Null values in fare: 1
Null values in cabin: 1014
Null values in embarked: 2
Null values in boat: 823
Null values in body: 1188
Null values in home.dest: 564


_____
3.Find out what the average age was and print "The average age was: mean"

In [4]:
age_mean = round(df['age'].mean(), 2) 
print(f'The average age was: {age_mean}')

The average age was: 29.88


_____
4. Create a table with the number of survivors divided by sex.

In [5]:
survivors = df.pivot_table(index='sex', aggfunc={'survived': sum})
survivors

survived
sex             
female       339
male         161

### Exercise 2

_____
1. Open the CSV file

In [6]:
df_2 = pd.read_csv('opsd_germany_daily.csv')
df_2

Date  Consumption     Wind   Solar  Wind+Solar
0     2006-01-01   1069.18400      NaN     NaN         NaN
1     2006-01-02   1380.52100      NaN     NaN         NaN
2     2006-01-03   1442.53300      NaN     NaN         NaN
3     2006-01-04   1457.21700      NaN     NaN         NaN
4     2006-01-05   1477.13100      NaN     NaN         NaN
...          ...          ...      ...     ...         ...
4378  2017-12-27   1263.94091  394.507  16.530     411.037
4379  2017-12-28   1299.86398  506.424  14.162     520.586
4380  2017-12-29   1295.08753  584.277  29.854     614.131
4381  2017-12-30   1215.44897  721.247   7.467     728.714
4382  2017-12-31   1107.11488  721.176  19.980     741.156

[4383 rows x 5 columns]

_____
2. Fill with 0 the missing values in Wind and Solar

In [7]:
df_2.Wind.fillna(0, inplace=True)
df_2['Solar'].fillna(0, inplace=True)
df_2

Date  Consumption     Wind   Solar  Wind+Solar
0     2006-01-01   1069.18400    0.000   0.000         NaN
1     2006-01-02   1380.52100    0.000   0.000         NaN
2     2006-01-03   1442.53300    0.000   0.000         NaN
3     2006-01-04   1457.21700    0.000   0.000         NaN
4     2006-01-05   1477.13100    0.000   0.000         NaN
...          ...          ...      ...     ...         ...
4378  2017-12-27   1263.94091  394.507  16.530     411.037
4379  2017-12-28   1299.86398  506.424  14.162     520.586
4380  2017-12-29   1295.08753  584.277  29.854     614.131
4381  2017-12-30   1215.44897  721.247   7.467     728.714
4382  2017-12-31   1107.11488  721.176  19.980     741.156

[4383 rows x 5 columns]

3) La columna de Wind+Solar debe coincidir con la suma de Wind y Solar

In [8]:
df_2.eval('`Wind+Solar`= Wind + Solar', inplace=True) 
df_2

Date  Consumption     Wind   Solar  Wind+Solar  \
0     2006-01-01   1069.18400    0.000   0.000         NaN   
1     2006-01-02   1380.52100    0.000   0.000         NaN   
2     2006-01-03   1442.53300    0.000   0.000         NaN   
3     2006-01-04   1457.21700    0.000   0.000         NaN   
4     2006-01-05   1477.13100    0.000   0.000         NaN   
...          ...          ...      ...     ...         ...   
4378  2017-12-27   1263.94091  394.507  16.530     411.037   
4379  2017-12-28   1299.86398  506.424  14.162     520.586   
4380  2017-12-29   1295.08753  584.277  29.854     614.131   
4381  2017-12-30   1215.44897  721.247   7.467     728.714   
4382  2017-12-31   1107.11488  721.176  19.980     741.156   

      BACKTICK_QUOTED_STRING_Wind_PLUS_Solar  
0                                      0.000  
1                                      0.000  
2                                      0.000  
3                                      0.000  
4                                      0.000  
...                                      ...  
4378                                 411.037  
4379                                 520.586  
4380                                 614.131  
4381                                 728.714  
4382                                 741.156  

[4383 rows x 6 columns]

In [9]:
df_2.drop('Wind+Solar', axis=1, inplace=True) 
df_2

Date  Consumption     Wind   Solar  \
0     2006-01-01   1069.18400    0.000   0.000   
1     2006-01-02   1380.52100    0.000   0.000   
2     2006-01-03   1442.53300    0.000   0.000   
3     2006-01-04   1457.21700    0.000   0.000   
4     2006-01-05   1477.13100    0.000   0.000   
...          ...          ...      ...     ...   
4378  2017-12-27   1263.94091  394.507  16.530   
4379  2017-12-28   1299.86398  506.424  14.162   
4380  2017-12-29   1295.08753  584.277  29.854   
4381  2017-12-30   1215.44897  721.247   7.467   
4382  2017-12-31   1107.11488  721.176  19.980   

      BACKTICK_QUOTED_STRING_Wind_PLUS_Solar  
0                                      0.000  
1                                      0.000  
2                                      0.000  
3                                      0.000  
4                                      0.000  
...                                      ...  
4378                                 411.037  
4379                                 520.586  
4380                                 614.131  
4381                                 728.714  
4382                                 741.156  

[4383 rows x 5 columns]

In [10]:
df_2.rename(columns={'BACKTICK_QUOTED_STRING_Wind_PLUS_Solar':'Wind+Solar'}, inplace=True)
df_2

Date  Consumption     Wind   Solar  Wind+Solar
0     2006-01-01   1069.18400    0.000   0.000       0.000
1     2006-01-02   1380.52100    0.000   0.000       0.000
2     2006-01-03   1442.53300    0.000   0.000       0.000
3     2006-01-04   1457.21700    0.000   0.000       0.000
4     2006-01-05   1477.13100    0.000   0.000       0.000
...          ...          ...      ...     ...         ...
4378  2017-12-27   1263.94091  394.507  16.530     411.037
4379  2017-12-28   1299.86398  506.424  14.162     520.586
4380  2017-12-29   1295.08753  584.277  29.854     614.131
4381  2017-12-30   1215.44897  721.247   7.467     728.714
4382  2017-12-31   1107.11488  721.176  19.980     741.156

[4383 rows x 5 columns]

_____
4. Create a pivot table that displays Wind + Solar consumption according to date, it must be vertical.

In [11]:
# check if there are null values
df_2.Consumption.isnull().sum()

0

In [12]:
table = df_2.pivot_table('Consumption', index='Date')
table

Consumption
Date                   
2006-01-01   1069.18400
2006-01-02   1380.52100
2006-01-03   1442.53300
2006-01-04   1457.21700
2006-01-05   1477.13100
...                 ...
2017-12-27   1263.94091
2017-12-28   1299.86398
2017-12-29   1295.08753
2017-12-30   1215.44897
2017-12-31   1107.11488

[4383 rows x 1 columns]

_____
5. Replace the missing values ​​of the pivot table with the mean.

In [13]:
table.fillna(df_2.Consumption.mean(), inplace=True)

_____
6. View the statistical data of the CSV in general.

In [14]:
df_2.describe()

Consumption         Wind        Solar   Wind+Solar
count  4383.000000  4383.000000  4383.000000  4383.000000
mean   1338.675836   109.800909    44.558071   154.358980
std     165.775710   140.698109    60.853561   165.174461
min     842.395000     0.000000     0.000000     0.000000
25%    1217.859000     0.000000     0.000000     0.000000
50%    1367.123000    62.293000     0.000000   123.808000
75%    1457.761000   162.366000    86.268000   248.019500
max    1709.568000   826.278000   241.580000   851.556000

____
7. Visualize the statistical data of the pivot table.

In [15]:
table.describe() 

Consumption
count  4383.000000
mean   1338.675836
std     165.775710
min     842.395000
25%    1217.859000
50%    1367.123000
75%    1457.761000
max    1709.568000

_____
8. Create 3 arrays: solar energy, wind energy and consumption.

In [16]:
solar_e = np.array(df_2.Solar)
wind_e = np.array(df_2.Wind)
consumption = np.array(df_2.Consumption)

In [17]:
solar_e

array([ 0.   ,  0.   ,  0.   , ..., 29.854,  7.467, 19.98 ])

In [18]:
wind_e

array([  0.   ,   0.   ,   0.   , ..., 584.277, 721.247, 721.176])

In [19]:
consumption

array([1069.184  , 1380.521  , 1442.533  , ..., 1295.08753, 1215.44897,
       1107.11488])